// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClKvHilyINzu_wufNpRZsYvrFopjM_KYA',
    appId: '1:458214207833:web:e8758fe12ed3cfe254dc48',
    messagingSenderId: '458214207833',
    projectId: 'school-app-731a4',
    authDomain: 'school-app-731a4.firebaseapp.com',
    storageBucket: 'school-app-731a4.firebasestorage.app',
    measurementId: 'G-8DNE67NV70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbg1y4GJk9wC_gdr5urQxRNpcVa5x4SMA',
    appId: '1:458214207833:android:24ab96c6a87b6f4454dc48',
    messagingSenderId: '458214207833',
    projectId: 'school-app-731a4',
    storageBucket: 'school-app-731a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMLH3AuL6jhro9C-ZACgFcDH2O5zGj72E',
    appId: '1:458214207833:ios:d1252f9d71046f7854dc48',
    messagingSenderId: '458214207833',
    projectId: 'school-app-731a4',
    storageBucket: 'school-app-731a4.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMLH3AuL6jhro9C-ZACgFcDH2O5zGj72E',
    appId: '1:458214207833:ios:d1252f9d71046f7854dc48',
    messagingSenderId: '458214207833',
    projectId: 'school-app-731a4',
    storageBucket: 'school-app-731a4.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClKvHilyINzu_wufNpRZsYvrFopjM_KYA',
    appId: '1:458214207833:web:7030cc297061934754dc48',
    messagingSenderId: '458214207833',
    projectId: 'school-app-731a4',
    authDomain: 'school-app-731a4.firebaseapp.com',
    storageBucket: 'school-app-731a4.firebasestorage.app',
    measurementId: 'G-FFQWJSK1K3',
  );
}
